"""Common command-line paths for plots requiring external raw data or predictions."""
from __future__ import annotations

import os
from pathlib import Path


def add_plot_paths(parser, script_file, *, zarr=False, pairs=False):
    """Add path overrides with defaults relative to the plotting archive."""
    base = Path(script_file).resolve().parents[1]
    repo = base.parents[2]
    workspace = Path(os.environ.get("MAST_WORKSPACE_ROOT", repo.parent)).expanduser().resolve()
    data_root = Path(os.environ.get("MAST_DATA_ROOT", workspace / "data")).expanduser().resolve()
    parser.add_argument("--preds-dir", type=Path, default=base / "data/preds", help="Directory containing test_predictions_<run>.npz.")
    parser.add_argument("--manifest", type=Path, default=base.parent / "test/split_test_real.jsonl", help="Test manifest used for predictions.")
    parser.add_argument("--output-dir", type=Path, default=base / "out", help="Directory for generated figures.")
    if zarr:
        local_raw = base / "data/raw/mast"
        default_raw = local_raw if local_raw.is_dir() else data_root / "raw/mast"
        parser.add_argument("--zarr-root", type=Path, default=default_raw, help="Directory containing <shot>.zarr and machine/<shot>/ geometry.")
    if pairs:
        parser.add_argument("--pairs", type=Path, default=base / "data/jtor_ip_pairs.npz", help="Current pairs generated by compute_jtor_pairs.py.")
